alter table "public"."donations" drop constraint "donations_pkey";

drop index if exists "public"."donations_pkey";

alter table "public"."donations" drop column "updated_at";

alter table "public"."donations" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX donations_id_key ON public.donations USING btree (id);

CREATE UNIQUE INDEX donations_pkey ON public.donations USING btree (profile_id, project_id, id);

alter table "public"."donations" add constraint "donations_pkey" PRIMARY KEY using index "donations_pkey";

alter table "public"."donations" add constraint "donations_id_key" UNIQUE using index "donations_id_key";

set check_function_bodies = off;


