create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null default ''::text,
    "discount" numeric not null default '0'::numeric,
    "image_url" text,
    "description" text not null default ''::text
);


alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX products_id_key ON public.products USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."products" add constraint "products_id_key" UNIQUE using index "products_id_key";

set check_function_bodies = off;


