create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text default ''::text,
    "last_name" text default ''::text,
    "birth_date" date,
    "location" text default ''::text,
    "want_difence_world" boolean default false,
    "want_diversify_portfolio" boolean default false,
    "want_tax_incentives" boolean default false,
    "want_specific_cause" boolean default false,
    "sdg" text[] default '{}'::text[],
    "profile_id" uuid
);


alter table "public"."user" enable row level security;

alter table "public"."profiles" drop column "age";

alter table "public"."profiles" drop column "avatar_url";

alter table "public"."profiles" drop column "completed_questionnaire";

alter table "public"."profiles" drop column "full_name";

alter table "public"."profiles" drop column "location";

alter table "public"."profiles" drop column "profile_picture";

alter table "public"."profiles" drop column "reason";

alter table "public"."profiles" drop column "sdg";

alter table "public"."profiles" drop column "username";

alter table "public"."profiles" drop column "want_difference_world";

alter table "public"."profiles" drop column "want_diversify_portfolio";

alter table "public"."profiles" drop column "want_specific_cause";

alter table "public"."profiles" drop column "want_tax_incentives";

alter table "public"."profiles" drop column "website";

alter table "public"."profiles" add column "email" text default ''::text;

alter table "public"."profiles" add column "user_id" bigint;

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."profiles" add constraint "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) not valid;

alter table "public"."profiles" validate constraint "profiles_user_id_fkey";

alter table "public"."user" add constraint "user_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user" validate constraint "user_profile_id_fkey";


